# Generated by Django 3.0.8 on 2020-07-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default='my_default'),
            preserve_default=False,
        ),
    ]
